//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccShiftDuty
    {
        public System.Guid AccountingID { get; set; }
        public System.Guid ShiftID { get; set; }
        public bool IsDutyDoctor { get; set; }
    
        public virtual AccountingWork AccountingWork { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
