//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDischarge
    {
        public System.Guid DischargeID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.Guid DrugID1 { get; set; }
        public System.Guid DrugID2 { get; set; }
        public System.Guid DrugID3 { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Drug Drug1 { get; set; }
        public virtual Drug Drug2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
