//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historyilling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historyilling()
        {
            this.PatientCards = new HashSet<PatientCard>();
        }
    
        public System.Guid HistoryillingID { get; set; }
        public System.Guid IllingID { get; set; }
        public System.Guid AnalysisID { get; set; }
        public string AnalysisResult { get; set; }
        public System.DateTime DatePatientilling { get; set; }
        public string PatientCondition { get; set; }
    
        public virtual Analyze Analyze { get; set; }
        public virtual Illing Illing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientCard> PatientCards { get; set; }
    }
}
