//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientCard()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid PatientCardNum { get; set; }
        public System.DateTime CardCreatingDate { get; set; }
        public string CardOwnerFIO { get; set; }
        public Nullable<System.Guid> HistoryillingID { get; set; }
    
        public virtual Historyilling Historyilling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
